describe('RaisingNOC', () => {
    it('initiate', () => {
        cy.visit('http://172.16.10.4:8082/jw/web/login')
        cy.get('#j_username').type('admin')
        cy.get('#j_password').type('Tomcat@123')
        cy.get('button[name="submit"]').click()
        cy.wait(10000)
        cy.get('#apps')
            .contains('Quality Control')
            .click()
        cy.get('.current-category > .menu-link').click()
        cy.get('#category-container')
            .contains('CANNIBALIZATION FORM')
            .click()
        cy.get('#grid > div.k-header.k-grid-toolbar > a:nth-child(2)').click()
        cy.get('#gp_dte').type('abc')
        cy.get('#work_center').type('abc')
        cy.get(':nth-child(3) > .k-widget > .k-picker-wrap > .k-select').click()
        cy.get('.k-footer > .k-link').click()
        cy.get('input[name="cfr"]').type('123456')
        cy.get('#trade').type('test')
        cy.get('#shop').type('test')
        cy.get('#remarks').type('test')
        cy.get('#oicName').type('test')
        cy.get('#oicDesignation').type('test')
        cy.get('#noun').type('test')
        cy.get('#partno').type('test')
        cy.get('#serialno').type('test')
        cy.get('#ac_hours_install').type('test')
        cy.get('#serialno_remove').type('test')
        cy.get('#ac_hours_remove').type('test')
        cy.get('#serialno_installon').type('test')
        cy.get('#serialno_can').type('test')
        cy.get('#remarks_dce').type('test')
        cy.get('#dceName').type('test')
        cy.get('#dceDesignation').type('test')
        cy.get('input[value="APPROVED"]').click()
        cy.get('#remarks_dce_1').clear()
        cy.get('#remarks_dce_1').type('test')
        cy.get('#ceName').type('test')
        cy.get('#ceDesignation').type('test')
        cy.get('#CompSNo1').type('test')
        cy.get('#1rank1').type('test')
        cy.get('#Sign1').type('test')
        cy.get('#Section1').type('test')
        cy.get('#ComponentDD829card1').type('test')
        cy.get('#AFTOform781Efolder1').type('test')
        cy.get('#CompWSheetSet1').type('test')
        cy.get('#CompFlowLineBook1').type('test')
        cy.get('#ActionedBy1').type('test')
       // cy.get('#submit').click()
    })
})


